name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Har 12 ghante me run karega
  workflow_dispatch:        # Manual run ka option

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ghanshyampratap
          outputs: dist/snake.svg

      - name: Push Snake Animation to Output Branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generate Snake Animation"
          add: "dist/snake.svg"
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
